[book]
authors = ["Kyle Curtis"]
src = "src"
title = "Rustacean Handbook"
language = "en"
multilingual = false

[output.html]
git-repository-url = "https://github.com/kylecurtis/rustacean-handbook/"
default-theme = "ayu"
preferred-dark-theme = "ayu"
